import Link from 'next/link';
import { works } from '@/lib/data';
import { Art, Orbit, Icon, ButtonLink, Card } from '@/components/ui';
import { HomeSearch } from '@/components/catalog';

export default function Home() {
  return <div className="container">
    <section className="hero"><div className="hero-copy"><div className="eyebrow">Rumah bagi kreativitas lokal</div><h1><span className="motion-line">Karya lokal.</span><span className="motion-line">Cerita baru.</span><span className="motion-line"><span>Potensi tanpa batas.</span></span></h1><p>Temukan karya yang bikin brand kamu berbeda. Pilih lisensinya, dan ikut tumbuhkan peluang bagi kreatornya.</p><div className="actions"><ButtonLink href="/katalog">Jelajahi karya <Icon name="arrow"/></ButtonLink><ButtonLink href="/studio" variant="secondary">Saya kreator</ButtonLink></div><div className="hero-note"><span className="mini-avatars"><b>N</b><b>D</b><b>A</b></span><span><strong>Berawal dari karya. Bertumbuh bersama.</strong><br/>Kenali kreator lewat koleksi contoh kami.</span></div></div><div className="hero-collage"><div className="collage-label"><span className="pixel-dot"/> DARI KREATIVITAS, JADI IDENTITAS</div><Link className="collage-main" href="/karya/rona-tropis"><Art work={works[0]} priority/><div className="collage-caption"><span>Motif pilihan <strong>Rona Tropis</strong></span><span className="round-arrow">↗</span></div></Link><Link className="collage-small" href="/karya/ruang-warna" aria-label="Lihat Ruang Warna"><Art work={works[1]} priority/></Link><div className="royalty-note"><Icon name="chart"/><span><strong>80% untuk kreator</strong><small>Pembagian royalti simulasi</small></span></div><div className="orbit-peek"><Orbit/><span>Halo, ide baru!</span></div></div></section>
    <div className="trust-strip">{[['spark','Kenali cerita karyanya','Temukan kreator di balik karya.'],['file','Pilih skala penggunaan','Lisensi yang mengikuti kebutuhanmu.'],['chart','Lihat pembagian nilainya','Royalti kreator ditampilkan terbuka.']].map(([icon,title,description]) => <div className="trust-item" key={title}><div className="trust-icon"><Icon name={icon}/></div><div><h3>{title}</h3><p>{description}</p></div></div>)}</div>
    <section className="section"><div className="section-head"><div><div className="eyebrow">Koleksi pilihan</div><h2>Temukan klik kreatifmu.</h2><p>Karya dengan karakter, untuk ide yang punya arah.</p></div><ButtonLink href="/katalog" variant="text">Lihat semua <Icon name="arrow"/></ButtonLink></div><div className="home-search"><HomeSearch/></div><div className="art-grid">{works.map(work => <Card key={work.id} work={work}/>)}</div></section>
    <section className="how-block"><div className="how-intro"><span className="eyebrow">Sesederhana itu</span><h2>Dari inspirasi<br/>jadi kolaborasi.</h2><p>Hak cipta tetap di kreator.<br/>Kamu memilih hak penggunaannya.</p></div><div className="steps">{[['01','Temukan karyamu','Jelajahi motif dan ilustrasi yang cocok dengan cerita brand.'],['02','Pilih lisensinya','Tentukan skala penggunaan dan lihat pembagian nilainya.'],['03','Tumbuh bersama','Coba transaksi demo dan lihat royalti tercatat di studio.']].map(([number,title,description]) => <div key={number}><span>{number}</span><h3>{title}</h3><p>{description}</p></div>)}</div></section>
    <section className="creator-banner"><div><Orbit/></div><div><h2>Karyamu punya masa depan.</h2><p>Kenali bagaimana lisensi bisa membuka peluang pendapatan kreator.</p></div><ButtonLink href="/studio" variant="secondary">Lihat studio demo <Icon name="arrow"/></ButtonLink></section>
  </div>;
}
