'use client';
import { useHydrated } from '@/lib/purchases';
import { useState } from 'react';
import { money, quote, tiers } from '@/lib/data';
import { type Work, type Tier, isTier } from '@/lib/types';
import { Art, Back, ButtonLink, Icon, Rules, Split } from './ui';
import { AnimatedNumber } from './motion';
export function Detail({work:w, initialTier}: {work: Work; initialTier: Tier}) {
  const ready=useHydrated(); const [tier,setTier] = useState(initialTier); const q = quote(w.id,tier);
  return <div className="container page" data-motion-ready={ready}><Back href="/katalog">Kembali ke katalog</Back><div className="detail-layout"><section><div className="detail-art"><Art work={w} priority/><span className="badge">Contoh karya</span></div><div className="work-story"><div className="eyebrow">Di balik karya</div><h2>Setiap bentuk punya cerita.</h2><p>{w.description}</p><div className="creator-profile"><span className="avatar big">{w.creator[0]}</span><div><strong>{w.creator}</strong><p>Kreator contoh · {w.city}</p></div></div><div className="meta-row"><span>Kategori<strong>{w.category}</strong></span><span>Pratinjau<strong>Ilustrasi digital</strong></span><span>Kepemilikan<strong>Tetap di kreator</strong></span></div></div></section><section className="license-panel"><span className="overline">{w.category} / Koleksi contoh</span><h1>{w.title}</h1><p className="muted">oleh {w.creator} · {w.city}</p><fieldset className="tier-options"><legend>Pilih skala penggunaanmu</legend>{Object.entries(tiers).map(([key,t]) => <label className="tier-option" key={key}><input type="radio" name="tier" value={key} checked={key===tier} onChange={e=>{if(isTier(e.target.value))setTier(e.target.value);}}/><span><strong>{t.name}</strong><small>{t.short}</small></span><b>{money(w.prices[key as Tier])}</b></label>)}</fieldset><div id="tier-summary"><div className="terms"><h3>Contoh cakupan {tiers[tier].name}</h3><Rules tier={tier}/><p>Tidak termasuk penjualan ulang file sumber atau pengalihan hak cipta.</p></div><div className="price-row"><span>Total lisensi simulasi</span><strong><AnimatedNumber value={q.total}/></strong></div><Split quote={q} animate/><ButtonLink href={`/checkout/${w.id}?tier=${tier}`} variant="full">Lanjut ke simulasi <Icon name="arrow"/></ButtonLink></div><p className="fineprint">Ketentuan dan harga di atas adalah contoh. Pemeriksaan orisinalitas dan kontrak nyata belum tersedia pada demo.</p></section></div></div>;
}
