'use client';
import Image from 'next/image';
import { useHydrated, usePurchases, storageAvailable } from '@/lib/purchases';
import { dateLabel, getWork, money, quote, tiers } from '@/lib/data';
import { Art, Back, ButtonLink, Icon, Missing, Orbit, Rules, Split } from './ui';
export function Licenses() {
  const all=usePurchases(); const ready=useHydrated();
  return <div className="container page" data-motion-ready={ready}><div className="section-head"><div className="page-heading"><div className="eyebrow">Ruang penggunaanmu</div><h1>Lisensi saya<span>.</span></h1><p>Semua pilihan karyamu, dalam satu tempat.</p></div><ButtonLink href="/katalog" variant="secondary">Cari karya lagi <Icon name="arrow"/></ButtonLink></div>{!ready?<p role="status">Memuat lisensi…</p>:all.length?<div className="license-list">{all.map(p=>{const w=getWork(p.workId)!;return <article className="license-row" key={p.id}><Art work={w}/><div><span className="tag">Simulasi · {tiers[p.tier].name}</span><h3>{w.title}</h3><p>{w.creator} · {dateLabel(p.date)}</p></div><strong>{money(p.amount)}</strong><ButtonLink href={'/lisensi/'+p.id} variant="secondary small">Lihat ringkasan</ButtonLink></article>;})}</div>:<div className="empty"><Orbit/><h2>Cerita pertamamu menanti.</h2><p>Belum ada lisensi simulasi. Temukan karya,<br/>pilih penggunaan, lalu coba alur lisensinya.</p><ButtonLink href="/katalog">Jelajahi karya <Icon name="arrow"/></ButtonLink></div>}<p className="footnote">{!ready||storageAvailable?'Data lisensi tersimpan hanya pada browser ini.':'Penyimpanan browser tidak tersedia; data hanya bertahan dalam sesi ini.'} Semua dokumen merupakan simulasi.</p></div>;
}
export function License({id}: {id:string}) {
  const all=usePurchases(),ready=useHydrated(); const p=all.find(x=>x.id===id);
  if(!ready)return <div className="container page" role="status">Memuat ringkasan lisensi…</div>;
  if(!p)return <Missing/>;
  const w=getWork(p.workId)!,q=quote(p.workId,p.tier);
  return <div className="container page certificate-page"><Back href="/lisensi">Semua lisensi saya</Back><div className="success-heading"><Orbit/><div><span className="tag">Transaksi simulasi tercatat</span><h1>Karya bertemu<br/><span>peluang baru.</span></h1><p>Ringkasanmu siap. Royalti contoh sudah tercatat di studio.</p>{!storageAvailable&&<p role="status">Penyimpanan browser tidak tersedia; lisensi hanya bertahan dalam sesi ini.</p>}</div></div><section className="certificate"><div className="certificate-top"><Image src="/assets/logo.svg" alt="OTENTIK" width={145} height={36}/><span className="tag">DEMO • BUKAN KONTRAK</span></div><h2>Ringkasan lisensi {tiers[p.tier].name}</h2><p className="record-id">{p.id}</p><div className="certificate-work"><Art work={w}/><div><h3>{w.title}</h3><p>{w.creator} · {w.category}</p><strong>{money(q.total)}</strong></div></div><dl><div><dt>Pemegang contoh</dt><dd>Pembeli demo</dd></div><div><dt>Tanggal simulasi</dt><dd>{dateLabel(p.date)}</dd></div><div><dt>Jenis penggunaan</dt><dd>{tiers[p.tier].name}</dd></div><div><dt>Kepemilikan karya</dt><dd>Tetap di kreator</dd></div></dl><Rules tier={p.tier}/><Split quote={q}/><p className="fineprint">Dokumen ini tidak memberikan hak penggunaan nyata, bukan bukti pembayaran, dan tidak dapat digunakan sebagai kontrak lisensi.</p></section><div className="actions center"><ButtonLink href="/studio">Lihat royalti di studio <Icon name="arrow"/></ButtonLink><ButtonLink href="/katalog" variant="secondary">Temukan karya lain</ButtonLink></div></div>;
}
