export const works=[
 {id:'rona-tropis',title:'Rona Tropis',category:'Motif',creator:'Nara Studio',city:'Yogyakarta',image:'tropis.png',color:'#fff0da',description:'Ritme daun dan bunga tropis dalam palet biru, coral, dan kuning. Sebuah eksplorasi visual yang hangat untuk kemasan, kain, dan cerita brand sehari-hari.',tags:'bunga daun batik kemasan fashion tropis',prices:{personal:35000,umkm:75000,nasional:450000}},
 {id:'ruang-warna',title:'Ruang Warna',category:'Ilustrasi',creator:'Dimas Pradana',city:'Madiun',image:'geometris.png',color:'#edf4ff',description:'Pertemuan matahari, gelombang, dan bentuk geometris yang berani. Membawa energi segar untuk materi promosi serta identitas visual yang ekspresif.',tags:'geometri matahari laut abstrak promosi poster',prices:{personal:45000,umkm:125000,nasional:650000}},
 {id:'cerita-pasar',title:'Cerita Pasar',category:'Ilustrasi',creator:'Ayu Rupa',city:'Bandung',image:'pasar.png',color:'#fff2e9',description:'Warna-warni buah dan dedaunan merayakan suasana pasar yang hidup. Cocok untuk eksplorasi kemasan kuliner dan komunikasi brand yang ramah.',tags:'buah pasar makanan kuliner kemasan mangga',prices:{personal:30000,umkm:95000,nasional:500000}}
];
export const tiers={personal:{name:'Personal',short:'Untuk ide dan proyek pribadi',rules:['Proyek pribadi nonkomersial','Tidak untuk produk yang dijual','Atribusi kreator pada publikasi']},umkm:{name:'UMKM',short:'Untuk usaha kecil yang bertumbuh',rules:['Satu brand dan satu lini produk','Contoh batas: hingga 1.000 unit produk','Promosi digital untuk brand yang sama']},nasional:{name:'Brand Nasional',short:'Untuk jangkauan yang lebih luas',rules:['Satu brand, kampanye berskala nasional','Contoh batas: hingga 50.000 unit produk','Materi promosi digital dan cetak']}};
export const baseline=[{id:'ARSIP-001',workId:'rona-tropis',tier:'umkm',amount:75000,date:'2026-09-12T09:00:00.000Z',buyer:'Ruang Roti',seed:true},{id:'ARSIP-002',workId:'ruang-warna',tier:'personal',amount:45000,date:'2026-09-14T09:00:00.000Z',buyer:'Proyek pribadi',seed:true},{id:'ARSIP-003',workId:'cerita-pasar',tier:'umkm',amount:95000,date:'2026-09-16T09:00:00.000Z',buyer:'Kebun Kecil',seed:true}];
export const money=n=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(n);
export const dateLabel=value=>new Intl.DateTimeFormat('id-ID',{day:'numeric',month:'short',year:'numeric'}).format(new Date(value));
export const getWork=id=>works.find(w=>w.id===id);
export function quote(workId,tier){const work=getWork(workId);if(!work||!Object.hasOwn(tiers,tier))throw new Error('Karya atau tier tidak tersedia.');const total=work.prices[tier];return {total,creator:Math.round(total*.8),platform:total-Math.round(total*.8)};}
